# Generated by Django 5.1.5 on 2025-02-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersubscriptionmodel',
            name='start_date',
            field=models.DateField(),
        ),
    ]
