# Generated by Django 5.1.5 on 2025-02-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_membersubscriptionmodel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersubscriptionmodel',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
