# Generated by Django 5.1.5 on 2025-02-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_membersubscriptionmodel_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplanmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='membershipplanmodel',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='membersubscriptionmodel',
            name='end_date',
        ),
    ]
