# Generated by Django 5.1.5 on 2025-02-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_membermodel_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
