# Generated by Django 5.1.5 on 2025-02-16 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FitnessClassTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(null=True, upload_to='class/images/')),
                ('phone', models.CharField(max_length=12)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessClassBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.membermodel')),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.fitnessclassmodel')),
            ],
        ),
        migrations.AddField(
            model_name='fitnessclassmodel',
            name='time',
            field=models.ManyToManyField(to='class.fitnessclasstimemodel'),
        ),
        migrations.AddField(
            model_name='fitnessclassmodel',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.instructormodel'),
        ),
        migrations.AddField(
            model_name='instructormodel',
            name='specialization',
            field=models.ManyToManyField(to='class.specializationmodel'),
        ),
        migrations.AddField(
            model_name='fitnessclassmodel',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.specializationmodel'),
        ),
    ]
