# Generated by Django 5.1.5 on 2025-02-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructormodel',
            name='image',
            field=models.ImageField(null=True, upload_to='class/images/'),
        ),
    ]
