# Generated by Django 5.1.5 on 2025-02-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_instructormodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessclassbookingmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='fitnessclassbookingmodel',
            name='booking_date',
            field=models.DateField(default=None),
        ),
    ]
