# Generated by Django 5.1.5 on 2025-02-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_remove_fitnessclassbookingmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclassbookingmodel',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
